import type { SupabaseClient } from "@supabase/supabase-js"

// ============================================
// READ — SKUs & Products
// ============================================

/**
 * Returns SKU records by a list of IDs.
 * Includes stock, active status, price override, and parent product ID.
 */
export async function findSkusByIds(client: SupabaseClient, ids: string[]) {
  if (ids.length === 0) return []

  const { data, error } = await client
    .from("product_skus")
    .select("id, stock, active, product_id, price_override, sku_code")
    .in("id", ids)

  if (error) throw new Error(error.message)
  return data ?? []
}

/**
 * Returns product records by a list of IDs.
 * Includes stock, active, archived status, and price.
 */
export async function findProductsByIds(client: SupabaseClient, ids: string[]) {
  if (ids.length === 0) return []

  const { data, error } = await client
    .from("products")
    .select("id, stock, active, archived, price")
    .in("id", ids)

  if (error) throw new Error(error.message)
  return data ?? []
}

/**
 * Returns products by ID list including the reservation flag.
 * Used for cart validation to detect products with active reservations.
 */
export async function findProductsWithReservationFlag(
  client: SupabaseClient,
  ids: string[]
) {
  if (ids.length === 0) return []

  const { data, error } = await client
    .from("products")
    .select("id, name, price, stock, active, archived, has_active_reservation")
    .in("id", ids)

  if (error) throw new Error(error.message)
  return data ?? []
}

/**
 * Returns refreshed stock values for the given product IDs.
 * Called after expiring reservations to get up-to-date quantities.
 */
export async function findProductsStockByIds(
  client: SupabaseClient,
  ids: string[]
) {
  if (ids.length === 0) return []

  const { data, error } = await client
    .from("products")
    .select("id, stock")
    .in("id", ids)

  if (error) throw new Error(error.message)
  return data ?? []
}

/**
 * Returns a single product's archived status by its ID.
 */
export async function findProductArchivedStatus(
  client: SupabaseClient,
  productId: string
) {
  const { data, error } = await client
    .from("products")
    .select("archived")
    .eq("id", productId)
    .single()

  if (error) throw new Error(error.message)
  return data
}

// ============================================
// READ — Reservations
// ============================================

/**
 * Returns the count of active (pending) stock reservations.
 */
export async function countActiveReservations(client: SupabaseClient) {
  const { count, error } = await client
    .from("stock_reservations")
    .select("*", { count: "exact", head: true })
    .eq("status", "pending")

  if (error) throw new Error(error.message)
  return count ?? 0
}

// ============================================
// RPCs — Reservations
// ============================================

/**
 * Calls the DB function that expires all timed-out reservations globally.
 */
export async function cleanupExpiredReservations(client: SupabaseClient) {
  const { error } = await client.rpc("cleanup_expired_reservations")
  if (error) throw new Error(error.message)
}

/**
 * Calls the DB function that expires reservations for a specific product.
 */
export async function cleanupExpiredReservationsForProduct(
  client: SupabaseClient,
  productId: string
) {
  const { error } = await client.rpc(
    "cleanup_expired_reservations_for_product",
    { p_product_id: productId }
  )
  if (error) throw new Error(error.message)
}

/**
 * Creates a stock reservation for a set of cart items.
 * Returns the reservation ID generated by the DB.
 */
export async function createStockReservation(
  client: SupabaseClient,
  userId: string,
  items: unknown,
  reservationMinutes: number = 15
) {
  const { data, error } = await client.rpc("create_stock_reservation", {
    p_user_id: userId,
    p_items: items as any,
    p_reservation_minutes: reservationMinutes,
  })

  if (error) throw new Error(error.message)
  return data
}

// ============================================
// RPCs — Stock adjustments
// ============================================

/**
 * Increments the stock of a SKU variant.
 * Used when rolling back a declined/failed order.
 */
export async function incrementSkuStock(
  client: SupabaseClient,
  skuId: string,
  quantity: number
) {
  const { error } = await client.rpc("increment_sku_stock", {
    p_sku_id: skuId,
    p_quantity: quantity,
  })

  if (error) throw new Error(error.message)
}

/**
 * Increments the stock of a base product (no variant).
 * Used when rolling back a declined/failed order.
 */
export async function incrementProductStock(
  client: SupabaseClient,
  productId: string,
  quantity: number
) {
  const { error } = await client.rpc("increment_product_stock", {
    p_product_id: productId,
    p_quantity: quantity,
  })

  if (error) throw new Error(error.message)
}
